FROM openjdk:17-jdk-slim
EXPOSE 8085
ADD target/Ask-Buddy_MS-Contact_Us-0.0.1-SNAPSHOT.jar Ask-Buddy_MS-Contact_Us-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","/Ask-Buddy_MS-Contact_Us-0.0.1-SNAPSHOT.jar"]